const express = require("express");
const cors = require("cors");
require("dotenv").config();

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

// Test route
app.get("/", (req, res) => {
  res.json({
    message: "RentRide Backend is running successfully 🚗🏍️",
  });
});

// Cars API
app.get("/api/cars", (req, res) => {
  const cars = [
    {
      id: 1,
      brand: "Toyota",
      model: "Camry",
      image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb",
      year: 2024,
      location: "Hyderabad",
      rating: 4.8,
      seats: 5,
      transmission: "Automatic",
      fuel: "Petrol",
      category: "Sedan",
      price: 2500,
    },
    {
      id: 2,
      brand: "Hyundai",
      model: "Creta",
      image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6",
      year: 2024,
      location: "Hyderabad",
      rating: 4.7,
      seats: 5,
      transmission: "Automatic",
      fuel: "Petrol",
      category: "SUV",
      price: 3000,
    },
    {
      id: 3,
      brand: "BMW",
      model: "3 Series",
      image: "https://images.unsplash.com/photo-1555215695-3004980ad54e",
      year: 2023,
      location: "Hyderabad",
      rating: 4.9,
      seats: 5,
      transmission: "Automatic",
      fuel: "Petrol",
      category: "Luxury",
      price: 5000,
    },
    {
      id: 4,
      brand: "Mercedes-Benz",
      model: "C-Class",
      image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8",
      year: 2024,
      location: "Hyderabad",
      rating: 4.9,
      seats: 5,
      transmission: "Automatic",
      fuel: "Petrol",
      category: "Luxury",
      price: 6000,
    },
    {
      id: 5,
      brand: "Audi",
      model: "A4",
      image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6",
      year: 2023,
      location: "Hyderabad",
      rating: 4.8,
      seats: 5,
      transmission: "Automatic",
      fuel: "Petrol",
      category: "Luxury",
      price: 5500,
    },
    {
      id: 6,
      brand: "Mahindra",
      model: "Thar",
      image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf",
      year: 2024,
      location: "Hyderabad",
      rating: 4.7,
      seats: 4,
      transmission: "Manual",
      fuel: "Diesel",
      category: "SUV",
      price: 3500,
    },
    {
      id: 7,
      brand: "Kia",
      model: "Seltos",
      image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2",
      year: 2024,
      location: "Hyderabad",
      rating: 4.6,
      seats: 5,
      transmission: "Automatic",
      fuel: "Petrol",
      category: "SUV",
      price: 2800,
    },
    {
      id: 8,
      brand: "Honda",
      model: "City",
      image: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8",
      year: 2023,
      location: "Hyderabad",
      rating: 4.6,
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      category: "Sedan",
      price: 2200,
    },
    {
      id: 9,
      brand: "Tata",
      model: "Nexon",
      image: "https://images.unsplash.com/photo-1550355291-bbee04a92027",
      year: 2024,
      location: "Hyderabad",
      rating: 4.5,
      seats: 5,
      transmission: "Automatic",
      fuel: "Petrol",
      category: "SUV",
      price: 2400,
    },
    {
      id: 10,
      brand: "Toyota",
      model: "Fortuner",
      image: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
      year: 2024,
      location: "Hyderabad",
      rating: 4.8,
      seats: 7,
      transmission: "Automatic",
      fuel: "Diesel",
      category: "SUV",
      price: 4500,
    },
  ];

  res.json(cars);
});

// Bikes API
app.get("/api/bikes", (req, res) => {
  const bikes = [
    {
      id: 1,
      brand: "Royal Enfield",
      model: "Classic 350",
      image: "https://images.unsplash.com/photo-1558981806-ec527fa84c39",
      year: 2024,
      location: "Hyderabad",
      rating: 4.8,
      seats: 2,
      transmission: "Manual",
      fuel: "Petrol",
      category: "Cruiser",
      price: 1200,
    },
    {
      id: 2,
      brand: "Yamaha",
      model: "MT-15",
      image: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc",
      year: 2024,
      location: "Hyderabad",
      rating: 4.7,
      seats: 2,
      transmission: "Manual",
      fuel: "Petrol",
      category: "Sports",
      price: 1000,
    },
    {
      id: 3,
      brand: "KTM",
      model: "Duke 390",
      image: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87",
      year: 2023,
      location: "Hyderabad",
      rating: 4.9,
      seats: 2,
      transmission: "Manual",
      fuel: "Petrol",
      category: "Sports",
      price: 1500,
    },
    {
      id: 4,
      brand: "Royal Enfield",
      model: "Hunter 350",
      image: "https://images.unsplash.com/photo-1558980664-10ea7e7b8c8a",
      year: 2024,
      location: "Hyderabad",
      rating: 4.7,
      seats: 2,
      transmission: "Manual",
      fuel: "Petrol",
      category: "Roadster",
      price: 1100,
    },
    {
      id: 5,
      brand: "Yamaha",
      model: "R15 V4",
      image: "https://images.unsplash.com/photo-1558980394-0c0d5f3c9d5a",
      year: 2024,
      location: "Hyderabad",
      rating: 4.8,
      seats: 2,
      transmission: "Manual",
      fuel: "Petrol",
      category: "Sports",
      price: 1300,
    },
    {
      id: 6,
      brand: "Kawasaki",
      model: "Ninja 300",
      image: "https://images.unsplash.com/photo-1580310614729-ccd69652491d",
      year: 2023,
      location: "Hyderabad",
      rating: 4.8,
      seats: 2,
      transmission: "Manual",
      fuel: "Petrol",
      category: "Sports",
      price: 1800,
    },
    {
      id: 7,
      brand: "Honda",
      model: "CB350",
      image: "https://images.unsplash.com/photo-1609630875171-b1321377ee65",
      year: 2024,
      location: "Hyderabad",
      rating: 4.6,
      seats: 2,
      transmission: "Manual",
      fuel: "Petrol",
      category: "Cruiser",
      price: 1150,
    },
    {
      id: 8,
      brand: "TVS",
      model: "Apache RTR 200",
      image: "https://images.unsplash.com/photo-1611241443320-2d8d4e5f6e1d",
      year: 2023,
      location: "Hyderabad",
      rating: 4.6,
      seats: 2,
      transmission: "Manual",
      fuel: "Petrol",
      category: "Sports",
      price: 950,
    },
    {
      id: 9,
      brand: "Bajaj",
      model: "Dominar 400",
      image: "https://images.unsplash.com/photo-1558981852-426c6a5a7a1f",
      year: 2024,
      location: "Hyderabad",
      rating: 4.7,
      seats: 2,
      transmission: "Manual",
      fuel: "Petrol",
      category: "Touring",
      price: 1400,
    },
    {
      id: 10,
      brand: "BMW",
      model: "G 310 R",
      image: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87",
      year: 2024,
      location: "Hyderabad",
      rating: 4.9,
      seats: 2,
      transmission: "Manual",
      fuel: "Petrol",
      category: "Roadster",
      price: 2000,
    },
  ];

  res.json(bikes);
});

// Start server
app.listen(PORT, () => {
  console.log(`RentRide Backend running on http://localhost:${PORT}`);
});